"""Add pid to Execution

Revision ID: 02715a2e718b
Revises: 5601549f7a15
Create Date: 2026-04-18 14:24:54.565913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02715a2e718b'
down_revision = '5601549f7a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_column('pid')

    # ### end Alembic commands ###
