"""add workflow schedule and execution workflow_id

Revision ID: 2db1b386fcc7
Revises: d998a9c4c65b
Create Date: 2026-04-15 18:50:32.788302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db1b386fcc7'
down_revision = 'd998a9c4c65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_exec_workflow', 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('schedule_value', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('schedule_value')
        batch_op.drop_column('schedule_type')

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exec_workflow', type_='foreignkey')
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###
