"""Add max_iterations to Workflow

Revision ID: 5601549f7a15
Revises: 30c7ccfd56a4
Create Date: 2026-04-18 10:38:49.312176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5601549f7a15'
down_revision = '30c7ccfd56a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_iterations', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('max_iterations')

    # ### end Alembic commands ###
