"""add job chains

Revision ID: f2f45507bd84
Revises: ca2f9304207c
Create Date: 2026-04-15 16:41:37.559935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f45507bd84'
down_revision = 'ca2f9304207c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_node_positions',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('job_chains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_job_id', sa.String(), nullable=False),
    sa.Column('target_job_id', sa.String(), nullable=False),
    sa.Column('trigger_condition', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['target_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_job_id', 'target_job_id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_by_execution_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('triggered_by_chain_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_exec_chain', 'job_chains', ['triggered_by_chain_id'], ['id'])
        batch_op.create_foreign_key('fk_exec_parent', 'executions', ['triggered_by_execution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exec_chain', type_='foreignkey')
        batch_op.drop_constraint('fk_exec_parent', type_='foreignkey')
        batch_op.drop_column('triggered_by_chain_id')
        batch_op.drop_column('triggered_by_execution_id')

    op.drop_table('job_chains')
    op.drop_table('chain_node_positions')
    # ### end Alembic commands ###
